name: Publish other repos

on:
  push:
  release:
    types: [published]


permissions:
    contents: write

jobs:
    upload-repos:
        # container:
        #   image: ubuntu:22.04
        #   options: --privileged
        



        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
            - name: upload repos
              run: |
                # for every repo in default_repos.yaml create a zip file and upload it to the release

                # get the list of packages from repos.yaml
                packages=$(yq e '.repositories[].url' "$repos_file")
                branches=$(yq e '.repositories[].version' "$repos_file")

                i=1
                for package in $packages; do
                    branch=$(echo "$branches" | sed -n "${i}p")
                    i=$((i + 1))
                    echo "Processing $package on branch $branch"
                    git clone "$package" --branch "$branch"
                    repo_name=$(basename "$package" .git)
                    zip -r "$repo_name".zip "$repo_name"
                done
            - name: Push to release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: "*.zip"
